### ISSUE TITLE
判断是否突破网速限制成功

### ISSUE THREAD

**Issue by laizhangtu** [flipped-1121/AutoLogin#11]
经过测试发现，解除限速的关键是公网ip，等到公网ip不是自己的时候，限制就解除了，所以可以添加个循环来稳定突破限制

**Comment by nyakang** [comment]
> 经过测试发现，解除限速的关键是公网ip，等到公网ip不是自己的时候，限制就解除了，所以可以添加个循环来稳定突破限制

本人已不在学校，欢迎测试后提交 PR !

**Comment by laizhangtu** [comment]
> > 经过测试发现，解除限速的关键是公网ip，等到公网ip不是自己的时候，限制就解除了，所以可以添加个循环来稳定突破限制
> 
> 本人已不在学校，欢迎测试后提交 PR !

好的，谢谢大佬之前的开发
